# Generated by Django 5.2.1 on 2025-05-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('medical_condition', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
